### ISSUE TITLE
Import module failure

### ISSUE THREAD

**Issue by herepete** [amosbastian/fpl#10]
Just a heads up

On Python 3.4.8  & fpl==0.5.0
 to fpl.py i had to ammend the top of the file to 

```
import sys

sys.path.append('/usr/lib/python3.4/site-packages/fpl')

from constants import API_URLS
from classic_league import ClassicLeague
#from fixture import Fixture
from gameweek import Gameweek
from h2h_league import H2HLeague
from player import Player
from team import Team
from user import User

```
to get it working

great stuff though :)

**Comment by amosbastian** [comment]
Hi @herepete, thanks for the heads up! I think this has been fixed in 0.5.2. Could you upgrade the package and confirm this?
