### ISSUE TITLE
How can I see a team based on player's entry?

### ISSUE THREAD

**Issue by razinc** [amosbastian/fpl#101]
Hello,

This is my code:
```python
from fpl import FPL
import aiohttp
import asyncio

async def main():
    async with aiohttp.ClientSession() as session:
        fpl = FPL(session)
        await fpl.login()
        user = await fpl.get_user(user_id = 4865323)
        team = await user.get_team()

asyncio.run(main())
```
Error:
Exception: User ID does not match provided email address!

I can get this to work if I change the `user_id` to mine but the intention of this code block is to see another player's team.

Thanks.

**Comment by amosbastian** [comment]
As it says, `user.get_team() returns a logged in user’s current team. You can't see another user's team without being logged into their account on the website either. Use `user.get_picks()` instead.

**Comment by razinc** [comment]
Thanks @amosbastian for your help.
