### ISSUE TITLE
user.transfer works but returns error for mimetype

### ISSUE THREAD

**Issue by rmikhael** [amosbastian/fpl#102]
Running the following python script:

```
#!/usr/bin/python3

import asyncio
import aiohttp
from fpl import FPL

async def my_team(user_id):
     async with aiohttp.ClientSession() as session:
         fpl = FPL(session)
         await fpl.login("someemail.com", "somepassword")
         user = await fpl.get_user(user_id)
         #await user.substitute([12],[213]).   # works
         #await user.captain(213).                  # works
         await user.transfer([437],[514]).      # works but gives error
         team = await user.get_team()
     print(user)
     print(team)

asyncio.run(my_team(111111))
```

Makes the correct transfer, but gives out the following error:

> Traceback (most recent call last):
>   File "/Users/rmikhael/Downloads/./test.py", line 19, in <module>
>     asyncio.run(my_team(836745))
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
>     return future.result()
>   File "/Users/rmikhael/Downloads/./test.py", line 14, in my_team
>     await user.transfer([514],[437])
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/fpl/models/user.py", line 589, in transfer
>     post_response = await post(
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/fpl/utils.py", line 27, in post
>     return await response.json()
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1097, in json
>     raise ContentTypeError(
> aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://fantasy.premierleague.com/api/transfers/')

my python3 version is 3.9.1
my fpl version is 0.6.25

I know I can suppress the error by calling
$ python3 test.py 2> /dev/null

But I would rather have a clean response with no errors, since I want my code to verify no errors from calling the script.

**Comment by amosbastian** [comment]
I noticed this as well a while ago and did some research. From this I think that the problem lies in the `Content-Type` of the server's response, which is not under our control. However, in the weekend I will have another look if I have time and see if I can somehow ignore the warning.

**Comment by amosbastian** [comment]
Sorry for the late response. I had a look last weekend but couldn't figure it out and don't really have time to fix it. 😞
