### ISSUE TITLE
Many fixtures are inaccurate

### ISSUE THREAD

**Issue by AllanDannUnder** [amosbastian/fpl#103]
When running the following code to print out all the fixtures per gameweek, the promoted teams seem to be missing, and other than that, some other fixtures are also incorrect. Relegated teams from 20/21 are still in the data.

```python
import aiohttp
from fpl import FPL
import asyncio

async def main():
    async with aiohttp.ClientSession() as session:
        fpl = FPL(session)

        for gw in range(1, 39):
            print(gw)
            fixtures = await fpl.get_fixtures_by_gameweek(gw)
            for fix in range(len(fixtures)):
                print(fixtures[fix])

asyncio.get_event_loop().run_until_complete(main())
```

### Here is the output for GW 1:

- Brighton vs. Arsenal - Fri 13 Aug 19:00
- Man Utd vs. Leeds - Sat 14 Aug 11:30
- Chelsea vs. Burnley - Sat 14 Aug 14:00
- Crystal Palace vs. Everton - Sat 14 Aug 14:00
- Fulham vs. Southampton - Sat 14 Aug 14:00
- Leicester vs. Wolves - Sat 14 Aug 14:00
- West Brom vs. Aston Villa - Sat 14 Aug 14:00
- Sheffield Utd vs. Liverpool - Sat 14 Aug 16:30
- Newcastle vs. West Ham - Sun 15 Aug 13:00
- Spurs vs. Man City - Sun 15 Aug 15:30

### Here are the actual fixtures for GW 1 (corrections are in bold):

- **Brentford** vs. Arsenal - Fri 13 Aug 19:00
- Man Utd vs. Leeds - Sat 14 Aug 11:30
- **Burnley** vs. **Brighton** - Sat 14 Aug 14:00
- **Chelsea** vs. **Crystal Palace** - Sat 14 Aug 14:00
- **Everton** vs. Southampton - Sat 14 Aug 14:00
- Leicester vs. Wolves - Sat 14 Aug 14:00
- **Watford** vs. Aston Villa - Sat 14 Aug 14:00
- **Norwich** vs. Liverpool - Sat 14 Aug 16:30
- Newcastle vs. West Ham - Sun 15 Aug 13:00
- Spurs vs. Man City - Sun 15 Aug 15:30

**Comment by amosbastian** [comment]
I think it's just because the [`team_converter`](https://github.com/amosbastian/fpl/blob/master/fpl/utils.py#L57) and [`short_name_converter`](https://github.com/amosbastian/fpl/blob/2f27613974c872c39179d268d219a072f3dd9be9/fpl/utils.py#L85) functions need to be updated. I'll probably have some time to do it tomorrow.
