### ISSUE TITLE
403 on login

### ISSUE THREAD

**Issue by oystein-beaufort** [amosbastian/fpl#120]
Hi! Thanks for making this wrapper!

Everything worked well for a while until I started to get 403 when calling `fpl.login`:

```
Traceback (most recent call last):
  File "./scripts/fetch_league.py", line 389, in <module>
    asyncio.run(
  File "/Users/owh/.pyenv/versions/3.8.1/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/Users/owh/.pyenv/versions/3.8.1/lib/python3.8/asyncio/base_events.py", line 612, in run_until_complete
    return future.result()
  File "./scripts/fetch_league.py", line 88, in fetch_league_data
    await fpl.login(email, password)
  File "/Users/owh/code/fplstats/env/lib/python3.8/site-packages/fpl/fpl.py", line 634, in login
    state = response.url.query["state"]
KeyError: 'state'
```

As you can se there's also a minor bug when the login fails, but that's not important. I'm more interested in how to solve the 403 issue, if possible.

The printed response looks like this:
```
<ClientResponse(https://users.premierleague.com/accounts/login/) [403 Forbidden]>
<CIMultiDictProxy('Connection': 'keep-alive', 'Content-Length': '545', 'Server': 'nginx/1.18.0', 'Content-Type': 'text/html;charset=utf-8', 'X-DataDome': 'protected', 'Accept-CH': 'Sec-CH-UA,Sec-CH-UA-Mobile,Sec-CH-UA-Platform,Sec-CH-UA-Arch,Sec-CH-UA-Full-Version-List,Sec-CH-UA-Model,Sec-CH-Device-Memory', 'Charset': 'utf-8', 'Cache-Control': 'max-age=0, private, no-cache, no-store, must-revalidate', 'Pragma': 'no-cache', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Expose-Headers': 'x-dd-b, x-set-cookie', 'Access-Control-Allow-Origin': '*', 'X-DataDome-CID': 'AHrlqAAAAAMAvbyOxC2A3d4Aw4t9vA==', 'Set-Cookie': 'datadome=V9jlyTq9myIzxBdSfq0u59~EyY0.93SxLjV7PZeSGBZZ-_1-pc3_p.KT9dnGU84mNeFTM1F2.itU8p1-zt0wurVOBSI2vGvm~4_3YOBnjnZiEnzxhCH0YOFICFeGvW9; Max-Age=31536000; Domain=.premierleague.com; Path=/; Secure; SameSite=Lax', 'Via': '1.1 google, 1.1 varnish', 'Accept-Ranges': 'bytes', 'Date': 'Sun, 15 May 2022 15:06:49 GMT', 'X-Served-By': 'cache-cph20628-CPH', 'X-Cache': 'MISS', 'X-Cache-Hits': '0')>
```

Any idea how I can avoid getting 403 on logins? I guess it could be a security mechanism they use to block suspicious logins.. 🤔

**Comment by amosbastian** [comment]
I think it's because of the new captcha they have added since they are planning on adding 2FA next season, but not sure. There have been quite a few other people with this problem on the Discord server, maybe you can find some workarounds there 😄

**Comment by oystein-beaufort** [comment]
Ah, yeah, that makes sense! Thanks, will do:) Will post here if I find a workaround

**Comment by kernalkue** [comment]
I'm hitting this issue. Any luck @oystein-beaufort ?

**Comment by oyshan** [comment]
Nope @kernalkue, you just have to avoid doing too many logins (from the same machine/IP) in the same time period

**Comment by oyshan** [comment]
This can probably be closed as it's not something that can be solved by this package, I think. @amosbastian

**Comment by razinc** [comment]
> Nope @kernalkue, you just have to avoid doing too many logins (from the same machine/IP) in the same time period

HI @oyshan, may I know what do you mean by avoid doing too many logins? I only login once and seeing this error.
