### ISSUE TITLE
Install problem 

### ISSUE THREAD

**Issue by Zamanov84** [amosbastian/fpl#13]
Hi! 

After installing with pip install fpl I get the following error when importing fpl in Jupyter: 
ModuleNotFoundError: No module named 'fpl.models'

How can I fix this? 
Thanks!

**Comment by herepete** [comment]
I tested and had a similar error yesterday after updating via pip, I won’t be near a computer for a few days to give more specific feedback

Sent from my iPhone

On 6 Oct 2018, at 09:01, Zamanov84 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi!

After installing with pip install fpl I get the following error when importing fpl in Jupyter:
ModuleNotFoundError: No module named 'fpl.models'

How can I fix this?
Thanks!
