### ISSUE TITLE
Add missing env vars requirements to README / DOCS

### ISSUE THREAD

**Issue by espoem** [amosbastian/fpl#22]
It appears that one needs to be logged in to be able use fpl fully. The FPL class gets email and password values from the env vars if not provided as input params. Since there is no mention in the docs that it is required to have the env vars set, fpl.login() will fail on KeyError exception. Consequently, tests relying on fpl.login() fail.

Required env vars are FPL_EMAIL, FPL_PASSWORD

**Comment by amosbastian** [comment]
Is this fixed with your recent commits?

**Comment by espoem** [comment]
It was fixed. Though, I'd say you can mention the env vars as one can set email and password with them instead of passing email and password as input params in login()
