### ISSUE TITLE
Update CLI to work with asyncio

### ISSUE THREAD

**Issue by amosbastian** [amosbastian/fpl#27]
Currently the CLI is broken because the functions aren't awaited. I am guessing you need to add some kind of decorator to the functions to make this work with asyncio.

**Comment by dmallory42** [comment]
I could take a look at this if you'd like @amosbastian?

**Comment by amosbastian** [comment]
Sure @dmallory42, that would be great, so go ahead! A word of caution: @espoem told me today a lot more is broken other than it just not working with asyncio (I haven't touched it since updating the entire package to work asynchronously, so it's completely outdated), which means getting the CLI back up and running is a lot more work than just making it work with asyncio. I'll definitely be available to help if this seems a bit too daunting for your first issue, so just @ me on Discord or here!

**Comment by espoem** [comment]
Hey @dmallory42, are you working on this issue?

**Comment by dmallory42** [comment]
Hi @espoem, I was planning on but to be honest I haven't had a chance to have a look at it yet (I've been much busier than I expected!). If you wanted to also take a look at it I don't mind at all!
