### ISSUE TITLE
2019/20 api change

### ISSUE THREAD

**Issue by wamburu** [amosbastian/fpl#36]
Seems the previous api endpoints are not working with the new season. Getting 404 error and the lib seems to be broken.

**Comment by Darkshines44** [comment]
The /drf/ part of the URL has changed to /api/.

Hope this can be easily fixed and look forward to new version of the FPL package!!

**Comment by amosbastian** [comment]
I'll look into this tomorrow, thanks for notifying me guys!

**Comment by wamburu** [comment]
What about the teams?  `https://fantasy.premierleague.com/api/teams` doesn't seem to be.

**Comment by jeski** [comment]
leagues has also changed.

**Comment by amosbastian** [comment]
I've updated it so the package still works for the preseason -- will fix everything properly once the season actually has started and all the new endpoints are set in stone.
