### ISSUE TITLE
Having an issue with tests and running simple examples

### ISSUE THREAD

**Issue by kahaanshah** [amosbastian/fpl#39]
Hi there! Thanks so much for this work! I'm a bit of a beginner so I'm not sure if I'm doing something very stupid. In that case, apologies for wasting your time. 

My code was working a few days ago; it's just a simple download all players. Now I get the error: 

File "fpl_load.py", line 13, in <module>
    asyncio.run(save_player())
  File "/anaconda3/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/anaconda3/lib/python3.7/asyncio/base_events.py", line 573, in run_until_complete
    return future.result()
  File "fpl_load.py", line 9, in save_player
    players = await fpl.get_player(150)
  File "/anaconda3/lib/python3.7/site-packages/fpl/fpl.py", line 219, in get_player
    players = players["elements"]
TypeError: 'NoneType' object is not subscriptable

The code I ran was: (I imported all modules above)

async def save_player():
	async with aiohttp.ClientSession() as session:
		fpl = FPL(session)
		players = await fpl.get_player(150)
		with open('player_data.pkl', 'wb') as output:
			#pickle.dump(players, output, pickle.HIGHEST_PROTOCOL)

asyncio.run(save_player())

**Comment by Helloimbob** [comment]
I'm also getting the same error - I'm a bit of a python noon but running it through the debugger it seems as though the request to the FPL API isn't retuning anything (at least when using the bootstrap-static URL)

Accessing the bootstrap-static URL from a browser appears to return the data correctly

**Comment by amosbastian** [comment]
Sorry for the late reply. I'll look into fixing everything once I get back from holiday in roughly two weeks, so hopefully everything will work before the season starts.

**Comment by amosbastian** [comment]
It should be (sort of) fixed now. They changed a lot of the API this year, and so I had to change / fix / remove stuff to get it working again.
