### ISSUE TITLE
fpl API endpoints

### ISSUE THREAD

**Issue by Gurminder08** [amosbastian/fpl#41]
First of all great library and documentation to know insights of the fpl.

Issue: Seems like API endpoints change from time to time. Even though most of the endpoints are working fine, but still some of them do not work. Can you provide a generalized way to confirm the endpoint if they change in the future.

thanks

**Comment by elrobak** [comment]
You can sniff them out by loading a page with the developer window (F12) open to the network tab and watching what fetch requests they make
![apiendpoints](https://user-images.githubusercontent.com/54073082/63005429-69155400-be74-11e9-99ee-3ef3ef2556ac.png)

Each of those fetch requests are the endpoints hit by my team's gameweek 1 entry, right clicking on them will let you copy the url.

**Comment by amosbastian** [comment]
What @elrobak said, but to make it even easier, also select XHR under the filter after clicking the network tab.
