### ISSUE TITLE
Player games_played property always returns 0

### ISSUE THREAD

**Issue by ChrisMusson** [amosbastian/fpl#46]
#### Expected behaviour
Should return the number of games where the minutes played by the relevant player is greater than 0

#### Actual behaviour
Returns 0 for all players

I think this happens because the fixtures attribute that games_played uses doesn't exist because the data needed has moved to a different endpoint. 

Using "https://fantasy.premierleague.com/api/element-summary/player_ID/" and returning 
`sum([1 for match in player["history"] if match["minutes"] > 0])` gives the desired result

**Comment by amosbastian** [comment]
Cheers! I've fixed it, but now you have to await it since it has to fetch the data if it isn't available.
