### ISSUE TITLE
_get_players in Fixture class

### ISSUE THREAD

**Issue by johnmadden86** [amosbastian/fpl#54]
doesn't return expected values

**Comment by liamhartley** [comment]
I think it should be this

```
    def _get_players(self, metric):
        """Helper function that returns a dictionary containing players for the
        given metric (away and home).
        """
        stats = getattr(self, "stats", [])
        for statistic in stats:
            if statistic['identifier'] == metric:
                return statistic
        return {}
```

**Comment by johnmadden86** [comment]
Yes, the 'identifier' tag is new in this season's api
Was wondering if returning a list is more useful?
https://github.com/johnmadden86/fpl-1/commit/768647482da500150fd9bcc63b321731cf21dc00

**Comment by liamhartley** [comment]
I personally think that the object might be more useful, because each one has inherent properties as well as separate statistics

**Comment by liamhartley** [comment]
I think it only filters if you return statistic[metric] as opposed to just returning statistic

**Comment by johnmadden86** [comment]
statistic's keys are 'identifier', 'a' and 'h'
The metric parameter is the value of the 'identifier' being sought from the stats list
Reformatting the stats list as a dict upon init would do the work of all the other methods.
see my new commit
