### ISSUE TITLE
How to get team ID of the logged in user

### ISSUE THREAD

**Issue by nikolal** [amosbastian/fpl#56]
```
    async with aiohttp.ClientSession() as session:
        fpl = FPL(session)
        await fpl.login(email=email, password=password)

        user = await fpl.get_user(?????????)
```

I want to automatically set id for logged in user. Is there a way to get this ID after I call login()?

**Comment by amosbastian** [comment]
I've just added some code that should set it automatically if you don't provide a user ID in `fpl.get_user`. Once the package has been updated to version 0.6.15 you can install it with

```
pip install fpl --upgrade
```
