### ISSUE TITLE
apply live total to players

### ISSUE THREAD

**Issue by johnmadden86** [amosbastian/fpl#62]
after calculating live bonus

**Comment by amosbastian** [comment]
Sorry I don't understand what you mean exactly. Could you provide an example?

**Comment by johnmadden86** [comment]
Add a "live_score" attribute to the player class, or just alter the "total_points" attribute.
The /live endpoint just has the element ids

**Comment by amosbastian** [comment]
I think it could work as a function in the `Player` class, what do you think? Or how do you see it being implemented?

**Comment by johnmadden86** [comment]
That's probably preferable - makes more sense for it to be structured that way
But it can't use the methods in the fpl class as it creates a circular reference.
The data from the /live endpoint will need to be passed as a parameter
