### ISSUE TITLE
update league tables with live data

### ISSUE THREAD

**Issue by johnmadden86** [amosbastian/fpl#64]

**Comment by amosbastian** [comment]
I'm not sure how viable this is, especially for leagues with thousands of users. What do you have in mind?

**Comment by johnmadden86** [comment]
Only want to do it for my league of 10 users.
Can try to add in something so that it won't process larger leagues, as it would take rather long I'm sure

**Comment by amosbastian** [comment]
I think you could do something that just does this for the 1st page which is at most 50 users if I recall correctly.
