### ISSUE TITLE
Pickling error with Player attribute '_session'

### ISSUE THREAD

**Issue by zwol3027** [amosbastian/fpl#80]
Is there a reason that the code needs to store '_session' as an attribute in the Player class?
It seems that games_played() is the only function that uses this attribute but could be changed not to use it.

This is an issue for me as:
I am trying to cache the player data using pickle, but I am unable to pickle the Players in their current form due to the '_session' attribute, as I get the error:
**AttributeError: Can't pickle local object 'WeakSet.__init__.<locals>._remove'**

**Comment by amosbastian** [comment]
I'll look into it and see if there is something I can change about it, but for now I think you can just remove the `_session` key before pickling a player? Like so:

```python
for player in players:
    del player["_session"]

# Pickle players after
```

**Comment by johnmadden86** [comment]
Not necessary, but probably preferable to keep it and move things like getting player summaries to this class
