### ISSUE TITLE
Classic League Issue

### ISSUE THREAD

**Issue by Srijan619** [amosbastian/fpl#82]
Hello,

The login seems to work but can't get any details from the classic leagues, even after logged in. Thought that they changed the link but it is still the same. I was working on a fetching the data from API from scratch and then suddenly found this repository, thought it would work, but it is not unfortunately. Could you confirm, if it is working for you, if so would like to know, what am i doing wrong.

Thanks
![Screenshot from 2020-03-16 14-22-42](https://user-images.githubusercontent.com/33220034/76758110-b0a8e900-6791-11ea-9dfd-7cf187da74b5.png)
![Screenshot from 2020-03-16 14-22-31](https://user-images.githubusercontent.com/33220034/76758113-b1417f80-6791-11ea-9c93-e4e6851b7bc8.png)

**Comment by amosbastian** [comment]
I'll check it out once I have some time! Thanks for reporting the issue 😄

**Comment by amosbastian** [comment]
Sorry for the late response, but are you sure the user ID matches with whatever credentials you are using to log in with?
