### ISSUE TITLE
user.get_user_history() hangs if user joined after gameweek 1

### ISSUE THREAD

**Issue by ffffuturexu** [amosbastian/fpl#83]
There is a bug in function get_user_history(). Similarly to [https://github.com/amosbastian/fpl/issues/34](url),  it hangs when user joined after gw1:

https://github.com/amosbastian/fpl/blob/c8620fc615dbb7b311c6fa246b78918d331b28d3/fpl/models/user.py#L347

where the code should be `range(self.started_event, self.current_event + 1)`

**Comment by amosbastian** [comment]
Thanks for pointing this out 😄 will fix it!
