### ISSUE TITLE
unable to get user_information from get_user()

### ISSUE THREAD

**Issue by obarbier** [amosbastian/fpl#87]
headers = {"User-Agent": "https://github.com/amosbastian/fpl"} from util looks like the cause of this, 
when changing user agent I was able to get the information

**Comment by amosbastian** [comment]
Can you provide the code where you encounter this error?

**Comment by obarbier** [comment]
user = await fplRequestApiServices.get_user(return_json=True)
    user_id = user['id']

**Comment by amosbastian** [comment]
Thanks, I pushed a new version where it is removed (and working). Not sure why this was happening in the first place 🤔

**Comment by obarbier** [comment]
thank you so much. any way I can contribute let me know. As I am a bit familiar with the code base now

**Comment by amosbastian** [comment]
Sounds great! If you have any ideas that you would want to work on just make a feature request @obarbier
