### ISSUE TITLE
Can we access previous year data from the player object

### ISSUE THREAD

**Issue by ajayrfhp** [amosbastian/fpl#89]
Can we get a list of scores obtained by a player in the previous FPL years ?

**Comment by amosbastian** [comment]
Do you mean this data?

![image](https://user-images.githubusercontent.com/9199433/91634566-96865e80-e9f1-11ea-9ed8-fd95c2c40999.png)

If so, then you can get this like this:

```python
from fpl import FPL
import aiohttp
import asyncio

async def main():
    async with aiohttp.ClientSession() as session:
        fpl = FPL(session)
        player = await fpl.get_player(1, include_summary=True)
    print(player.history_past)

asyncio.run(main())
```

If you mean points by week, then you would have to get it from something like this: https://github.com/vaastav/Fantasy-Premier-League

**Comment by ajayrfhp** [comment]
Yeah I need the points per week, I will checkout the link you posted. Thank you.
