### ISSUE TITLE
API requests loop indefinitely if request fails

### ISSUE THREAD

**Issue by 177arc** [amosbastian/fpl#90]
First of all, thank you, @amosbastian for creating this awesome library. I have based my [pandas-fpl](https://github.com/177arc/pandas-fpl) library on it!

Currently, if a request to the API returns anything apart from status 200, the fpl will try retry indefinitely. This an occur in a number of different scenarios, e.g. an invalid ID passed as a parameter.

Here is the relevant code section from utils.py:
```python
async def fetch(session, url):
    while True:
        try:
            async with session.get(url) as response:
                assert response.status == 200
                return await response.json()
        except Exception:
            pass
```

Infinite looping is a problem because a) the client does not get the opportunity to deal with any issues and b) the FPL API gets bombarded with requests.

Would it not be better so at least have the option to set a retry limit and raise an exception if no success?

**Comment by amosbastian** [comment]
Sounds like a good idea. Would you be willing to create a PR for this or should I do it myself?

**Comment by 177arc** [comment]
If it's quick for you, that would be great. Otherwise, I can give it a go but it may take a bit of time.

**Comment by amosbastian** [comment]
I think it should be fixed @177arc

**Comment by 177arc** [comment]
Excellent! Thank you very much!
