### ISSUE TITLE
Need an option to get my team details of any given gameweek

### ISSUE THREAD

**Issue by sreeniketh** [amosbastian/fpl#95]
I see that there is already an option for that in constants.py
"user_picks": "{}entry/{{}}/event/{{}}/picks/".format(API_BASE_URL)

There should be an easy function to take my user_id and gameweek_id to return my team details of that particular gameweek.
Could not find this in the documentation. If this already exists please let me know

**Comment by amosbastian** [comment]
Is [this](https://github.com/amosbastian/fpl/blob/master/fpl/models/user.py#L196) what you need?

**Comment by sreeniketh** [comment]
Yes thanks.
Could you add it to the documentation so that it is easier to find?

**Comment by amosbastian** [comment]
> Yes thanks.
> Could you add it to the documentation so that it is easier to find?

https://fpl.readthedocs.io/en/latest/classes/user.html#fpl.models.user.User.get_picks
