### ISSUE TITLE
Nonetype

### ISSUE THREAD

**Issue by colinobriencork** [amosbastian/fpl#96]
Hey I keep getting Nonetype when I try to run the basic tests. I'm pretty sure I've done everything right. Could it be that the endpoints are not updated for the new season?
Thanks!

**Comment by amosbastian** [comment]
A lot of tests aren't the best and could require you to have certain environment variables set (for testing logging in for example). I might have some time to check it out in the weekend. Could you paste the output that you get here?

**Comment by colinobriencork** [comment]
hey, sorry for the late reply, I got it working! Thanks anyway.
