### ISSUE TITLE
Adding list of packages to install / recommended Python Version

### ISSUE THREAD

**Issue by edwardjackchandler** [amosbastian/fpl#98]
Hi - as I'm trying to get the tests to work, I was running into a lot of missing packages. I'm not familiar with a lot of the libraries used, (mock, Sanic, pytest addons) and think it would be great to add a list of these dependencies to the Contributing part of the docs. I know it would have made my life easier to pickup this project starting with a list of dependencies / recommended Python Version.

First of all, is there a standard way to find these things out after cloning the repo? If not, I can collect what I've found to be the suite of packages that you need to install before test will work and add it to the contributing page.

**Comment by amosbastian** [comment]
You should be able to run `pip install .` in the repository after cloning it (or `pip install -e .` to install everything in editable mode).
